//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectCV.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbMvcCvEntities : DbContext
    {
        public DbMvcCvEntities()
            : base("name=DbMvcCvEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblAbout> TblAbouts { get; set; }
        public virtual DbSet<TblAboutPerson> TblAboutPersons { get; set; }
        public virtual DbSet<TblEducation> TblEducations { get; set; }
        public virtual DbSet<TblExperience> TblExperiences { get; set; }
        public virtual DbSet<TblProject> TblProjects { get; set; }
        public virtual DbSet<TblReference> TblReferences { get; set; }
        public virtual DbSet<TblSkill> TblSkills { get; set; }
    }
}
