//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectCV.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblEducation
    {
        public int id { get; set; }
        public string title { get; set; }
        public string subtitle { get; set; }
        public string department { get; set; }
        public string date { get; set; }
        public Nullable<decimal> gpa { get; set; }
    }
}
