//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectCV.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblReference
    {
        public int id { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string department { get; set; }
        public string company { get; set; }
        public string position { get; set; }
        public string phone { get; set; }
    }
}
